services:
  marker-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marker-api
    ports:
      - "8000:8000"
    environment:
      - TORCH_DEVICE=cpu # Change to 'cuda' if you have GPU support
      - PYTHONUNBUFFERED=1
    volumes:
      - ./temp_processing:/app/temp # Temporary processing directory
      - ./source_pdfs:/app/input # Mount input directory
      - marker_models:/root/.cache/datalab/models # Persist ML models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 300s # Longer startup time for build
    restart: unless-stopped

volumes:
  temp_processing:
    driver: local
  marker_models:
    driver: local
